name: Create release on tag

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: packages/os
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Set version and environment variables
      - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo "VERSION_IS_SEMVER=$(if [[ '${{ env.VERSION }}' =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV
      - run: echo "PREFIX=$(if [ '${{ env.VERSION_IS_SEMVER }}' = 'true' ]; then echo ''; else echo $(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]')-; fi)" >> $GITHUB_ENV
      - run: echo "TAG=$(echo ${{ github.repository_owner }}/${{ env.PREFIX }}umbrelos:${{ env.VERSION }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Build Docker image for amd64
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64 --file umbrelos.Dockerfile --tag ghcr.io/${{ env.TAG }} --push ../../
      - run: mkdir -p build && docker buildx imagetools inspect ghcr.io/${{ env.TAG }} > build/docker-umbrelos-${{ env.VERSION }}

      # Build OS image for amd64
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run build:amd64

      # Compress amd64 image
      - name: Compress release assets
        run: |
          cd build
          sudo xz --keep --threads=0 umbrelos-amd64.img

      # Create release directory with only required files
      - name: Create release directory
        run: |
          mkdir -p release
          mv build/docker-umbrelos-${{ env.VERSION }} release/
          mv build/umbrelos-amd64.update release/
          mv build/umbrelos-amd64.img.xz release/

      - name: Create SHASUM
        run: cd release && shasum -a 256 * | tee SHA256SUMS

      - name: OpenTimestamps
        run: npm ci && npx ots-cli.js stamp release/SHA256SUMS

      - name: Upload to R2
        uses: ryand56/r2-upload-action@b801a390acbdeb034c5e684ff5e1361c06639e7c # v1.4
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: packages/os/release
          destination-dir: ./${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          draft: true
          name: umbrelOS ${{ github.ref_name }}
          files: |
            packages/os/release/SHA256SUMS*
            packages/os/release/umbrelos-amd64.update
            packages/os/release/umbrelos-amd64.img.xz
