name: Create release on tag

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: packages/os
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Set version and environment variables
      - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo "VERSION_IS_SEMVER=$(if [[ '${{ env.VERSION }}' =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV
      - run: echo "PREFIX=$(if [ '${{ env.VERSION_IS_SEMVER }}' = 'true' ]; then echo ''; else echo $(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]')-; fi)" >> $GITHUB_ENV
      - run: echo "TAG=$(echo ${{ github.repository_owner }}/${{ env.PREFIX }}umbrelos:${{ env.VERSION }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Build Docker image for amd64
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64 --file umbrelos.Dockerfile --tag ghcr.io/${{ env.TAG }} --push ../../
      - run: mkdir -p build && docker buildx imagetools inspect ghcr.io/${{ env.TAG }} > build/docker-umbrelos-${{ env.VERSION }}

      # Build OS image for amd64
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run build:amd64

      # Compress amd64 image
      - name: Compress release assets
        run: |
          cd build
          sudo xz --keep --threads=0 umbrelos-amd64.img

      # Create release directory with only required files
      - name: Create release directory
        run: |
          mkdir -p release
          mv build/docker-umbrelos-${{ env.VERSION }} release/
          mv build/umbrelos-amd64.update release/
          mv build/umbrelos-amd64.img.xz release/

      - name: Create SHASUM
        run: cd release && shasum -a 256 * | tee SHA256SUMS

      - name: OpenTimestamps
        run: npm ci && npx ots-cli.js stamp release/SHA256SUMS

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: false # Cambiar a false para que el release no sea un borrador
          name: umbrelOS ${{ github.ref_name }}
          files: |
            packages/os/release/*
